[package]
name = "githubapi"
version = "0.1.0"
authors = ["Kim Hermansson <k.hermansson@adnymics.com>"]
edition = "2018"

[dependencies]
reqwest = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
